

const SUPABASE_URL='https://ltffbxrggflevlilqmze.supabase.co',SUPABASE_KEY='sb_publishable_svtQE6pna4HvyU07igxRnA_eUdi0rNJ',sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));const rupiah=n=>'Rp '+new Intl.NumberFormat('id-ID',{maximumFractionDigits:0}).format(Number(n||0));let rows=[],activeCat='all';
function categoryOf(x){const s=[x.title,x.product_name,x.description].join(' ').toLowerCase();if(/joki|boost|rank|jasa|service|followers|channel/.test(s))return'jasa';if(/mobile legend|mlbb|pubg|valorant|roblox|steam|game|diamond|voucher game|top up/.test(s))return'game';if(/spotify|netflix|disney|wetv|drive|canva|youtube|premium|akun|digital|voucher/.test(s))return'digital';return'other'}
function iconOf(x){const c=categoryOf(x),s=[x.title,x.product_name].join(' ').toLowerCase();if(s.includes('spotify'))return'♫';if(s.includes('netflix'))return'N';if(s.includes('whatsapp'))return'◉';if(s.includes('drive'))return'△';if(s.includes('mobile legend'))return'ML';if(c==='game')return'🎮';if(c==='jasa')return'⚡';if(c==='digital')return'◇';return'Y'}
async function load(){const {data,error}=await sb.rpc('get_marketplace_listings');if(error){$('#grid').innerHTML='<div class="empty">'+esc(error.message)+'</div>';return}rows=data||[];$('#statListings').textContent=rows.length;$('#statStores').textContent=new Set(rows.map(x=>x.store_name).filter(Boolean)).size;render()}
function render(){const q=$('#search').value.trim().toLowerCase(),f=rows.filter(x=>(activeCat==='all'||categoryOf(x)===activeCat)&&(!q||[x.title,x.product_name,x.store_name,x.seller_name,x.description].some(v=>String(v||'').toLowerCase().includes(q))));$('#countChip').textContent=f.length+' listing';$('#grid').innerHTML=f.length?f.map(x=>`<article class="card"><div class="visual ${categoryOf(x)}"><span class="new">Aktif</span><div class="visualGlow"></div><div class="productIcon">${esc(iconOf(x))}</div><div class="visualCopy"><b>${esc(x.product_name||x.title)}</b><span>${esc(categoryOf(x)==='game'?'Game & Top Up':categoryOf(x)==='jasa'?'Digital Service':categoryOf(x)==='digital'?'Digital Premium':'YANSTORE')}</span></div></div><div class="cardbody"><div class="storeRow"><span class="storeAvatar">${esc((x.store_name||'Y').slice(0,1).toUpperCase())}</span><span>${esc(x.store_name||x.seller_name||'YANSTORE Seller')}</span></div><div class="cardTitle">${esc(x.title)}</div><div class="desc">${esc(x.description||x.product_name||'Produk digital YANSTORE')}</div><div class="price">${rupiah(x.sell_price)}</div><div class="cardMeta"><span>Seller: ${esc(x.seller_name||'-')}</span><span class="stock">Stok ${Number(x.stock||0)}</span></div><button class="buyBtn" data-id="${esc(x.listing_id)}">Checkout</button></div></article>`).join(''):'<div class="empty">Belum ada listing yang cocok dengan pencarian atau kategori ini.</div>';document.querySelectorAll('.buyBtn').forEach(btn=>btn.addEventListener('click',()=>openOrder(btn.dataset.id)))}
function updateCheckoutSummary(){const unit=Number($('#orderUnitPrice').value||0),qty=Number($('#orderQty').value||1);$('#summaryUnit').textContent=rupiah(unit);$('#summaryQty').textContent=qty;$('#summaryTotal').textContent=rupiah(unit*qty)}
function openOrder(id){const x=rows.find(r=>String(r.listing_id)===String(id));if(!x)return;$('#orderListingId').value=x.listing_id;$('#orderTitle').textContent=x.title;$('#orderStore').textContent='Toko: '+x.store_name;$('#orderPrice').textContent=rupiah(x.sell_price);$('#orderUnitPrice').value=Number(x.sell_price||0);$('#orderStock').value=Math.max(1,Number(x.stock||1));$('#orderQty').value=1;$('#buyerName').value='';$('#buyerContact').value='';$('#buyerEmail').value='';$('#buyerNote').value='';$('#orderSuccess').classList.remove('show');$('#orderNext').classList.remove('show');$('#submitOrder').disabled=false;$('#submitOrder').textContent='Buat Pesanan';updateCheckoutSummary();$('#orderModal').classList.add('open')}
$('#qtyMinus').onclick=()=>{const q=Math.max(1,Number($('#orderQty').value||1)-1);$('#orderQty').value=q;updateCheckoutSummary()};
$('#qtyPlus').onclick=()=>{const stock=Math.max(1,Number($('#orderStock').value||1)),q=Math.min(stock,Number($('#orderQty').value||1)+1);$('#orderQty').value=q;updateCheckoutSummary()};
$('#submitOrder').onclick=async()=>{const id=$('#orderListingId').value,name=$('#buyerName').value.trim(),contact=$('#buyerContact').value.trim(),email=$('#buyerEmail').value.trim(),qty=Math.max(1,Number($('#orderQty').value||1));let note=$('#buyerNote').value.trim();if(!id||name.length<2||contact.length<5){alert('Lengkapi nama buyer dan WhatsApp / kontak.');return}$('#submitOrder').disabled=true;$('#submitOrder').textContent='Membuat pesanan...';const {data,error}=await sb.rpc('create_marketplace_order_v30',{p_listing_id:id,p_quantity:qty,p_buyer_name:name,p_buyer_contact:contact,p_buyer_email:email||null,p_buyer_note:note||null});if(error){$('#submitOrder').disabled=false;$('#submitOrder').textContent='Buat Pesanan';alert(error.message);return}const result=Array.isArray(data)?data[0]:data;$('#orderCode').textContent=result?.order_code||'-';$('#orderSuccess').classList.add('show');$('#orderNext').classList.add('show');document.querySelectorAll('.checkoutStep').forEach(x=>x.classList.add('active'));$('#submitOrder').textContent='Pesanan Dibuat';await load()};
$('#cancelOrder').onclick=()=>$('#orderModal').classList.remove('open');$('#orderModal').addEventListener('click',e=>{if(e.target===$('#orderModal'))$('#orderModal').classList.remove('open')});$('#search').oninput=render;$('#searchButton').onclick=()=>{render();$('#products').scrollIntoView({behavior:'smooth'})};document.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{activeCat=b.dataset.cat;document.querySelectorAll('.cat').forEach(x=>x.classList.toggle('active',x===b));render();$('#products').scrollIntoView({behavior:'smooth'})});document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'}));load();
