

const SUPABASE_URL='https://ltffbxrggflevlilqmze.supabase.co';
const SUPABASE_KEY='sb_publishable_svtQE6pna4HvyU07igxRnA_eUdi0rNJ';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const rupiah=n=>'Rp '+new Intl.NumberFormat('id-ID',{maximumFractionDigits:0}).format(Number(n||0));
let seller=null,orders=[],marketplaceOrders=[],ledger=[],withdrawals=[],catalog=[],listings=[];
async function forgotPassword(){const email=$('#email').value.trim();if(!email){$('#loginMsg').textContent='Isi email seller terlebih dahulu.';return}$('#loginMsg').textContent='Mengirim link reset password...';const redirectTo=new URL('seller.html',location.href).href;const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo});$('#loginMsg').textContent=error?error.message:'Link reset password sudah dikirim. Buka email seller lalu klik link tersebut.'}
async function handleRecovery(){const hash=new URLSearchParams(location.hash.replace(/^#/,'')),query=new URLSearchParams(location.search);const isRecovery=hash.get('type')==='recovery'||query.get('type')==='recovery';if(!isRecovery)return false;const pw=prompt('Buat password baru seller (minimal 6 karakter):');if(!pw)return true;if(pw.length<6){alert('Password minimal 6 karakter.');return true}const {error}=await sb.auth.updateUser({password:pw});if(error)alert(error.message);else{alert('Password seller berhasil diperbarui. Silakan login kembali.');await sb.auth.signOut();history.replaceState({},document.title,location.pathname);location.reload()}return true}
async function signIn(){$('#loginMsg').textContent='Memproses...';const {data,error}=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error){$('#loginMsg').textContent=error.message;return}await boot(data.user)}
async function signUp(){const email=$('#email').value.trim(),password=$('#password').value;if(!email||password.length<6){$('#loginMsg').textContent='Isi email seller dan password minimal 6 karakter.';return}$('#loginMsg').textContent='Membuat akun seller...';const {data,error}=await sb.auth.signUp({email,password});if(error){$('#loginMsg').textContent=error.message;return}if(data.session){$('#loginMsg').textContent='Akun berhasil dibuat. Sekarang lengkapi pengajuan toko.';$('#applyBox').classList.remove('hidden')}else $('#loginMsg').textContent='Akun dibuat. Konfirmasi email terlebih dahulu, lalu login untuk mengajukan toko.'}
async function boot(user){$('#loginMsg').textContent='Memeriksa akun seller...';let {data:s,error}=await sb.from('sellers').select('*').eq('auth_user_id',user.id).maybeSingle();if(error){$('#loginMsg').textContent=error.message;return}if(!s){$('#loginMsg').textContent='Akun aktif. Lengkapi pengajuan toko untuk menjadi seller YANSTORE.';$('#applyBox').classList.remove('hidden');return}if(s.status==='pending'){$('#loginView').classList.add('hidden');$('#pendingView').classList.remove('hidden');$('#pendingText').textContent='Toko '+(s.store_name||'kamu')+' sedang direview admin YANSTORE. Kamu belum dapat membuat listing sampai status Approved.';return}if(s.status!=='approved'){$('#loginMsg').textContent='Akun seller sedang tidak aktif. Hubungi admin YANSTORE.';return}seller=s;$('#loginView').classList.add('hidden');$('#pendingView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#topName').textContent=s.display_name;$('#topStore').textContent=s.store_name||'';$('#avatar').textContent=(s.display_name||'S').slice(0,1).toUpperCase();$('#welcome').textContent='Halo, '+s.display_name+'!';await loadData()}
async function loadData(){const [a,b,c,d,e,f]=await Promise.all([sb.from('seller_orders').select('id,buyer_name,product_name,sell_price,seller_profit,status,created_at,completed_at').order('created_at',{ascending:false}),sb.from('seller_ledger').select('id,entry_type,amount,note,created_at').order('created_at',{ascending:false}),sb.from('withdrawal_requests').select('id,amount,destination_type,destination_account,destination_name,status,created_at,processed_at').order('created_at',{ascending:false}),sb.from('seller_product_catalog').select('id,product_name,stock,minimum_stock').order('product_name'),sb.from('seller_listings').select('id,product_id,title,description,sell_price,status,created_at,updated_at').order('updated_at',{ascending:false}),sb.from('marketplace_orders').select('id,order_code,buyer_name,buyer_contact,product_name,listing_title,sell_price,status,payment_status,created_at,completed_at').order('created_at',{ascending:false})]);const err=[a,b,c,d,e].find(x=>x.error)?.error;if(err){alert(err.message);return}orders=a.data||[];ledger=b.data||[];withdrawals=c.data||[];catalog=d.data||[];listings=e.data||[];marketplaceOrders=f.error?[]:(f.data||[]);render()}
function render(){const balance=ledger.reduce((n,x)=>n+Number(x.amount||0),0),pendingAmount=withdrawals.filter(x=>x.status==='pending').reduce((n,x)=>n+Number(x.amount||0),0),available=Math.max(0,balance-pendingAmount),allOrders=[...marketplaceOrders.map(x=>({...x,_marketplace:true})),...orders.map(x=>({...x,_marketplace:false}))].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));$('#kpiBalance').textContent=rupiah(balance);$('#kpiAvailable').textContent=rupiah(available);$('#kpiListings').textContent=listings.filter(x=>x.status==='active').length;$('#kpiOrders').textContent=allOrders.filter(x=>x.status==='Selesai').length;$('#orderRows').innerHTML=allOrders.length?allOrders.map(x=>`<tr><td>${esc(new Date(x.created_at).toLocaleDateString('id-ID'))}</td><td>${esc(x.buyer_name||'-')}${x._marketplace?`<div class="muted">${esc(x.order_code||'Marketplace')}</div>`:''}</td><td>${esc(x.listing_title||x.product_name)}${x._marketplace?'<div class="muted">Marketplace • '+esc(x.payment_status||'Belum Dibayar')+'</div>':''}</td><td>${rupiah(x.sell_price)}</td><td class="money">${x._marketplace?'-':rupiah(x.seller_profit)}</td><td><span class="badge ${x.status==='Selesai'?'ok':x.status==='Dibatalkan'?'bad':'wait'}">${esc(x.status)}</span></td></tr>`).join(''):'<tr><td colspan="6" class="muted" style="text-align:center;padding:28px">Belum ada order.</td></tr>';$('#ledgerRows').innerHTML=ledger.length?ledger.map(x=>`<tr><td>${esc(new Date(x.created_at).toLocaleString('id-ID'))}</td><td>${esc(x.entry_type)}</td><td class="money">${Number(x.amount)>=0?'+':''}${rupiah(x.amount)}</td><td>${esc(x.note||'-')}</td></tr>`).join(''):'<tr><td colspan="4" class="muted" style="text-align:center;padding:28px">Belum ada ledger.</td></tr>';$('#withdrawRows').innerHTML=withdrawals.length?withdrawals.map(x=>`<tr><td>${esc(new Date(x.created_at).toLocaleDateString('id-ID'))}</td><td class="money">${rupiah(x.amount)}</td><td>${esc(x.destination_type+' • '+x.destination_account+' • '+x.destination_name)}</td><td><span class="badge ${x.status==='paid'?'ok':x.status==='rejected'?'bad':'wait'}">${x.status==='paid'?'Dibayar':x.status==='rejected'?'Ditolak':'Menunggu'}</span></td></tr>`).join(''):'<tr><td colspan="4" class="muted" style="text-align:center;padding:28px">Belum ada withdrawal.</td></tr>';renderCatalog();renderListings()}
function renderCatalog(){const q=($('#catalogSearch').value||'').trim().toLowerCase(),rows=catalog.filter(x=>!q||String(x.product_name||'').toLowerCase().includes(q));$('#catalogGrid').innerHTML=rows.length?rows.map(x=>{const qty=Number(x.stock||0),min=Number(x.minimum_stock||0),label=qty<=0?'Habis':qty<=min?'Menipis':'Tersedia',cls=qty<=0?'bad':qty<=min?'wait':'ok',existing=listings.find(l=>l.product_id===x.id);return `<div class="productcard"><div class="productname">${esc(x.product_name)}</div><span class="badge ${cls}">${label}</span><div class="stocknum">${qty}</div><div class="muted">stok tersedia • read-only</div><div class="cardactions"><button class="btn primary" onclick="openListing('${x.id}')" ${qty<=0?'disabled':''}>${existing?'Edit Listing':'Jual Produk'}</button></div></div>`}).join(''):'<div class="muted">Produk tidak ditemukan atau belum ada stok yang dibagikan.</div>'}
function renderListings(){$('#listingGrid').innerHTML=listings.length?listings.map(l=>{const p=catalog.find(x=>x.id===l.product_id),qty=Number(p?.stock||0);return `<div class="listingcard"><div class="productname">${esc(l.title)}</div><div class="muted">${esc(p?.product_name||'Produk')}</div><div class="price">${rupiah(l.sell_price)}</div><div class="muted">${esc(l.description||'Tanpa deskripsi')}</div><div style="margin-top:10px"><span class="badge ${l.status==='active'?'ok':'wait'}">${l.status==='active'?'Tayang':'Dijeda'}</span> <span class="badge ${qty>0?'ok':'bad'}">Stok ${qty}</span></div><div class="cardactions"><button class="btn" onclick="openListing('${l.product_id}')">Edit</button><button class="btn ${l.status==='active'?'danger':'primary'}" onclick="toggleListing('${l.id}','${l.status==='active'?'paused':'active'}')">${l.status==='active'?'Jeda':'Tayangkan'}</button></div></div>`}).join(''):'<div class="muted">Belum ada produk jualan. Buka Katalog Produk lalu klik <b>Jual Produk</b>.</div>'}
window.openListing=id=>{const p=catalog.find(x=>x.id===id);if(!p)return;const l=listings.find(x=>x.product_id===id);$('#listingProductId').value=id;$('#listingProductName').textContent='Produk sumber: '+p.product_name+' • stok '+p.stock;$('#listingName').value=l?.title||p.product_name;$('#listingPrice').value=l?.sell_price||'';$('#listingDesc').value=l?.description||'';$('#listingTitle').textContent=l?'Edit Listing Produk':'Buat Listing Produk';$('#listingModal').classList.add('open')};
window.toggleListing=async(id,status)=>{const {error}=await sb.rpc('set_seller_listing_status',{p_listing_id:id,p_status:status});if(error){alert(error.message);return}await loadData()};
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('.panel').forEach(p=>p.classList.toggle('active',p.id==='p-'+b.dataset.tab))});
$('#catalogSearch').oninput=renderCatalog;async function applyStore(){const name=$('#applyName').value.trim(),store=$('#applyStore').value.trim(),contact=$('#applyContact').value.trim(),desc=$('#applyDescription').value.trim();if(name.length<2||store.length<3||contact.length<5){$('#applyMsg').textContent='Lengkapi nama seller, nama toko, dan kontak.';return}$('#applyBtn').disabled=true;$('#applyMsg').textContent='Mengirim pengajuan...';const {data,error}=await sb.rpc('apply_public_seller',{p_display_name:name,p_store_name:store,p_contact:contact,p_store_description:desc||null});if(error){$('#applyBtn').disabled=false;$('#applyMsg').textContent=error.message;return}$('#applyMsg').textContent='Pengajuan berhasil dikirim. Menunggu approval admin.';const {data:{user}}=await sb.auth.getUser();if(user)await boot(user)}
$('#applyBtn').onclick=applyStore;
$('#pendingLogout').onclick=async()=>{await sb.auth.signOut();location.reload()};
$('#loginBtn').onclick=signIn;$('#signupBtn').onclick=signUp;$('#forgotBtn').onclick=forgotPassword;$('#password').onkeydown=e=>{if(e.key==='Enter')signIn()};$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};
$('#cancelListing').onclick=()=>$('#listingModal').classList.remove('open');$('#saveListing').onclick=async()=>{const productId=$('#listingProductId').value,title=$('#listingName').value.trim(),description=$('#listingDesc').value.trim(),price=Number($('#listingPrice').value||0);if(!productId||!title||price<=0){alert('Judul dan harga jual wajib diisi.');return}$('#saveListing').disabled=true;const {error}=await sb.rpc('upsert_seller_listing',{p_product_id:productId,p_title:title,p_description:description,p_sell_price:price});$('#saveListing').disabled=false;if(error){alert(error.message);return}$('#listingModal').classList.remove('open');await loadData();$$('[data-tab]').find(x=>x.dataset.tab==='listings')?.click();alert('Listing berhasil ditampilkan di Marketplace YANSTORE.')};
$('#requestBtn').onclick=()=>{$('#wdAmount').value='';$('#wdType').value='';$('#wdAccount').value='';$('#wdName').value='';$('#withdrawModal').classList.add('open')};$('#cancelWd').onclick=()=>$('#withdrawModal').classList.remove('open');$('#saveWd').onclick=async()=>{const amount=Number($('#wdAmount').value||0),type=$('#wdType').value.trim(),account=$('#wdAccount').value.trim(),name=$('#wdName').value.trim();if(amount<=0||!type||!account||!name){alert('Lengkapi nominal dan tujuan withdrawal.');return}$('#saveWd').disabled=true;const {error}=await sb.rpc('request_seller_withdrawal',{p_amount:amount,p_destination_type:type,p_destination_account:account,p_destination_name:name});$('#saveWd').disabled=false;if(error){alert(error.message);return}$('#withdrawModal').classList.remove('open');await loadData();alert('Permintaan withdrawal berhasil dikirim ke Bos.')};
(async()=>{if(await handleRecovery())return;const {data}=await sb.auth.getSession();if(data.session)await boot(data.session.user)})();
