-- HOME OFFICE V64 - ACCOUNT VAULT V2
-- Adds admin-only audit history for Data Akun actions.

create table if not exists public.account_vault_audit (
  id bigint generated by default as identity primary key,
  vault_item_id uuid references public.account_vault(id) on delete set null,
  action text not null,
  item_label text,
  detail text,
  actor_employee_id uuid references public.employees(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.account_vault_audit enable row level security;

grant select,insert on public.account_vault_audit to authenticated;

drop policy if exists "account_vault_audit_admin_select" on public.account_vault_audit;
create policy "account_vault_audit_admin_select"
on public.account_vault_audit
for select to authenticated
using (public.is_homeoffice_admin());

drop policy if exists "account_vault_audit_admin_insert" on public.account_vault_audit;
create policy "account_vault_audit_admin_insert"
on public.account_vault_audit
for insert to authenticated
with check (public.is_homeoffice_admin());

create index if not exists account_vault_audit_created_at_idx
on public.account_vault_audit(created_at desc);

create index if not exists account_vault_audit_item_idx
on public.account_vault_audit(vault_item_id);
